name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: ls all
        run:  ls src
      - name: Compile Java code
        run: javac src/Main.java

      - name: ls all
        run:  ls src

      - name: Run Java code
        run: java src/Main.class
