name: Java CI

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  printing:
    runs-on: ubuntu-latest
    steps:
      - name : print Hello!
        run : echo "Hello, World!"
