name: Java CI

on:
  push:

jobs:
  printing:
    runs-on: ubuntu-latest
    steps:
      - name : print Hello!
        run : echo "Hello, World!"


      - name : ls command
        run : ls -l

      - name : whoami command
        run : whoami

      - name : pwd where am i
        run : pwd

      - name: printALL!!
        run: ls /home -R





